//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonor_01.OnnoRokomSms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageHeader", Namespace="http://api.onnorokomsms.com/")]
    [System.SerializableAttribute()]
    public partial class MessageHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarskTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampingNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MarskText {
            get {
                return this.MarskTextField;
            }
            set {
                if ((object.ReferenceEquals(this.MarskTextField, value) != true)) {
                    this.MarskTextField = value;
                    this.RaisePropertyChanged("MarskText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CampingName {
            get {
                return this.CampingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CampingNameField, value) != true)) {
                    this.CampingNameField = value;
                    this.RaisePropertyChanged("CampingName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WsSms", Namespace="http://api.onnorokomsms.com/")]
    [System.SerializableAttribute()]
    public partial class WsSms : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SmsText {
            get {
                return this.SmsTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsTextField, value) != true)) {
                    this.SmsTextField = value;
                    this.RaisePropertyChanged("SmsText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.onnorokomsms.com/", ConfigurationName="OnnoRokomSms.SendSmsSoap")]
    public interface SendSmsSoap {
        
        // CODEGEN: Generating message contract since element name messageHeader from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToOneBulk", ReplyAction="*")]
        BloodDonor_01.OnnoRokomSms.OneToOneBulkResponse OneToOneBulk(BloodDonor_01.OnnoRokomSms.OneToOneBulkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToOneBulk", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.OneToOneBulkResponse> OneToOneBulkAsync(BloodDonor_01.OnnoRokomSms.OneToOneBulkRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToOne", ReplyAction="*")]
        BloodDonor_01.OnnoRokomSms.OneToOneResponse OneToOne(BloodDonor_01.OnnoRokomSms.OneToOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToOne", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.OneToOneResponse> OneToOneAsync(BloodDonor_01.OnnoRokomSms.OneToOneRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToMany", ReplyAction="*")]
        BloodDonor_01.OnnoRokomSms.OneToManyResponse OneToMany(BloodDonor_01.OnnoRokomSms.OneToManyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToMany", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.OneToManyResponse> OneToManyAsync(BloodDonor_01.OnnoRokomSms.OneToManyRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/DeliveryStatus", ReplyAction="*")]
        BloodDonor_01.OnnoRokomSms.DeliveryStatusResponse DeliveryStatus(BloodDonor_01.OnnoRokomSms.DeliveryStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/DeliveryStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.DeliveryStatusResponse> DeliveryStatusAsync(BloodDonor_01.OnnoRokomSms.DeliveryStatusRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetBalance", ReplyAction="*")]
        BloodDonor_01.OnnoRokomSms.GetBalanceResponse GetBalance(BloodDonor_01.OnnoRokomSms.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetBalanceResponse> GetBalanceAsync(BloodDonor_01.OnnoRokomSms.GetBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetMask", ReplyAction="*")]
        BloodDonor_01.OnnoRokomSms.GetMaskResponse GetMask(BloodDonor_01.OnnoRokomSms.GetMaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetMask", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetMaskResponse> GetMaskAsync(BloodDonor_01.OnnoRokomSms.GetMaskRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/NumberSms", ReplyAction="*")]
        BloodDonor_01.OnnoRokomSms.NumberSmsResponse NumberSms(BloodDonor_01.OnnoRokomSms.NumberSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/NumberSms", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.NumberSmsResponse> NumberSmsAsync(BloodDonor_01.OnnoRokomSms.NumberSmsRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/ListSms", ReplyAction="*")]
        BloodDonor_01.OnnoRokomSms.ListSmsResponse ListSms(BloodDonor_01.OnnoRokomSms.ListSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/ListSms", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.ListSmsResponse> ListSmsAsync(BloodDonor_01.OnnoRokomSms.ListSmsRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/SMSDeliveryStatus", ReplyAction="*")]
        BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusResponse SMSDeliveryStatus(BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/SMSDeliveryStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusResponse> SMSDeliveryStatusAsync(BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetCurrentBalance", ReplyAction="*")]
        BloodDonor_01.OnnoRokomSms.GetCurrentBalanceResponse GetCurrentBalance(BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetCurrentBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetCurrentBalanceResponse> GetCurrentBalanceAsync(BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetAllMask", ReplyAction="*")]
        BloodDonor_01.OnnoRokomSms.GetAllMaskResponse GetAllMask(BloodDonor_01.OnnoRokomSms.GetAllMaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetAllMask", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetAllMaskResponse> GetAllMaskAsync(BloodDonor_01.OnnoRokomSms.GetAllMaskRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneBulkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOneBulk", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.OneToOneBulkRequestBody Body;
        
        public OneToOneBulkRequest() {
        }
        
        public OneToOneBulkRequest(BloodDonor_01.OnnoRokomSms.OneToOneBulkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneBulkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BloodDonor_01.OnnoRokomSms.MessageHeader messageHeader;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public BloodDonor_01.OnnoRokomSms.WsSms[] wsSmses;
        
        public OneToOneBulkRequestBody() {
        }
        
        public OneToOneBulkRequestBody(BloodDonor_01.OnnoRokomSms.MessageHeader messageHeader, BloodDonor_01.OnnoRokomSms.WsSms[] wsSmses) {
            this.messageHeader = messageHeader;
            this.wsSmses = wsSmses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneBulkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOneBulkResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.OneToOneBulkResponseBody Body;
        
        public OneToOneBulkResponse() {
        }
        
        public OneToOneBulkResponse(BloodDonor_01.OnnoRokomSms.OneToOneBulkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneBulkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OneToOneBulkResult;
        
        public OneToOneBulkResponseBody() {
        }
        
        public OneToOneBulkResponseBody(string OneToOneBulkResult) {
            this.OneToOneBulkResult = OneToOneBulkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOne", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.OneToOneRequestBody Body;
        
        public OneToOneRequest() {
        }
        
        public OneToOneRequest(BloodDonor_01.OnnoRokomSms.OneToOneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobileNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string campaignName;
        
        public OneToOneRequestBody() {
        }
        
        public OneToOneRequestBody(string userName, string userPassword, string mobileNumber, string smsText, string type, string maskName, string campaignName) {
            this.userName = userName;
            this.userPassword = userPassword;
            this.mobileNumber = mobileNumber;
            this.smsText = smsText;
            this.type = type;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOneResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.OneToOneResponseBody Body;
        
        public OneToOneResponse() {
        }
        
        public OneToOneResponse(BloodDonor_01.OnnoRokomSms.OneToOneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OneToOneResult;
        
        public OneToOneResponseBody() {
        }
        
        public OneToOneResponseBody(string OneToOneResult) {
            this.OneToOneResult = OneToOneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToManyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToMany", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.OneToManyRequestBody Body;
        
        public OneToManyRequest() {
        }
        
        public OneToManyRequest(BloodDonor_01.OnnoRokomSms.OneToManyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToManyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string numberList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string smsType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string campaignName;
        
        public OneToManyRequestBody() {
        }
        
        public OneToManyRequestBody(string userName, string userPassword, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            this.userName = userName;
            this.userPassword = userPassword;
            this.messageText = messageText;
            this.numberList = numberList;
            this.smsType = smsType;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToManyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToManyResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.OneToManyResponseBody Body;
        
        public OneToManyResponse() {
        }
        
        public OneToManyResponse(BloodDonor_01.OnnoRokomSms.OneToManyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToManyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OneToManyResult;
        
        public OneToManyResponseBody() {
        }
        
        public OneToManyResponseBody(string OneToManyResult) {
            this.OneToManyResult = OneToManyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeliveryStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeliveryStatus", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.DeliveryStatusRequestBody Body;
        
        public DeliveryStatusRequest() {
        }
        
        public DeliveryStatusRequest(BloodDonor_01.OnnoRokomSms.DeliveryStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class DeliveryStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string responseId;
        
        public DeliveryStatusRequestBody() {
        }
        
        public DeliveryStatusRequestBody(string userName, string userPassword, string responseId) {
            this.userName = userName;
            this.userPassword = userPassword;
            this.responseId = responseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeliveryStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeliveryStatusResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.DeliveryStatusResponseBody Body;
        
        public DeliveryStatusResponse() {
        }
        
        public DeliveryStatusResponse(BloodDonor_01.OnnoRokomSms.DeliveryStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class DeliveryStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeliveryStatusResult;
        
        public DeliveryStatusResponseBody() {
        }
        
        public DeliveryStatusResponseBody(string DeliveryStatusResult) {
            this.DeliveryStatusResult = DeliveryStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.GetBalanceRequestBody Body;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(BloodDonor_01.OnnoRokomSms.GetBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        public GetBalanceRequestBody() {
        }
        
        public GetBalanceRequestBody(string userName, string userPassword) {
            this.userName = userName;
            this.userPassword = userPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.GetBalanceResponseBody Body;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(BloodDonor_01.OnnoRokomSms.GetBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBalanceResult;
        
        public GetBalanceResponseBody() {
        }
        
        public GetBalanceResponseBody(string GetBalanceResult) {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMask", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.GetMaskRequestBody Body;
        
        public GetMaskRequest() {
        }
        
        public GetMaskRequest(BloodDonor_01.OnnoRokomSms.GetMaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetMaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        public GetMaskRequestBody() {
        }
        
        public GetMaskRequestBody(string userName, string userPassword) {
            this.userName = userName;
            this.userPassword = userPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMaskResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.GetMaskResponseBody Body;
        
        public GetMaskResponse() {
        }
        
        public GetMaskResponse(BloodDonor_01.OnnoRokomSms.GetMaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetMaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMaskResult;
        
        public GetMaskResponseBody() {
        }
        
        public GetMaskResponseBody(string GetMaskResult) {
            this.GetMaskResult = GetMaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberSms", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.NumberSmsRequestBody Body;
        
        public NumberSmsRequest() {
        }
        
        public NumberSmsRequest(BloodDonor_01.OnnoRokomSms.NumberSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class NumberSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string messageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numberList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string campaignName;
        
        public NumberSmsRequestBody() {
        }
        
        public NumberSmsRequestBody(string apiKey, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            this.apiKey = apiKey;
            this.messageText = messageText;
            this.numberList = numberList;
            this.smsType = smsType;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberSmsResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.NumberSmsResponseBody Body;
        
        public NumberSmsResponse() {
        }
        
        public NumberSmsResponse(BloodDonor_01.OnnoRokomSms.NumberSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class NumberSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberSmsResult;
        
        public NumberSmsResponseBody() {
        }
        
        public NumberSmsResponseBody(string NumberSmsResult) {
            this.NumberSmsResult = NumberSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListSms", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.ListSmsRequestBody Body;
        
        public ListSmsRequest() {
        }
        
        public ListSmsRequest(BloodDonor_01.OnnoRokomSms.ListSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class ListSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public BloodDonor_01.OnnoRokomSms.WsSms[] wsSmses;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string campaignName;
        
        public ListSmsRequestBody() {
        }
        
        public ListSmsRequestBody(string apiKey, BloodDonor_01.OnnoRokomSms.WsSms[] wsSmses, string maskName, string campaignName) {
            this.apiKey = apiKey;
            this.wsSmses = wsSmses;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListSmsResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.ListSmsResponseBody Body;
        
        public ListSmsResponse() {
        }
        
        public ListSmsResponse(BloodDonor_01.OnnoRokomSms.ListSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class ListSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListSmsResult;
        
        public ListSmsResponseBody() {
        }
        
        public ListSmsResponseBody(string ListSmsResult) {
            this.ListSmsResult = ListSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMSDeliveryStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMSDeliveryStatus", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequestBody Body;
        
        public SMSDeliveryStatusRequest() {
        }
        
        public SMSDeliveryStatusRequest(BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class SMSDeliveryStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string responseId;
        
        public SMSDeliveryStatusRequestBody() {
        }
        
        public SMSDeliveryStatusRequestBody(string apiKey, string responseId) {
            this.apiKey = apiKey;
            this.responseId = responseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMSDeliveryStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMSDeliveryStatusResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusResponseBody Body;
        
        public SMSDeliveryStatusResponse() {
        }
        
        public SMSDeliveryStatusResponse(BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class SMSDeliveryStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMSDeliveryStatusResult;
        
        public SMSDeliveryStatusResponseBody() {
        }
        
        public SMSDeliveryStatusResponseBody(string SMSDeliveryStatusResult) {
            this.SMSDeliveryStatusResult = SMSDeliveryStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentBalance", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequestBody Body;
        
        public GetCurrentBalanceRequest() {
        }
        
        public GetCurrentBalanceRequest(BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetCurrentBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public GetCurrentBalanceRequestBody() {
        }
        
        public GetCurrentBalanceRequestBody(string apiKey) {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentBalanceResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.GetCurrentBalanceResponseBody Body;
        
        public GetCurrentBalanceResponse() {
        }
        
        public GetCurrentBalanceResponse(BloodDonor_01.OnnoRokomSms.GetCurrentBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetCurrentBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentBalanceResult;
        
        public GetCurrentBalanceResponseBody() {
        }
        
        public GetCurrentBalanceResponseBody(string GetCurrentBalanceResult) {
            this.GetCurrentBalanceResult = GetCurrentBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMask", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.GetAllMaskRequestBody Body;
        
        public GetAllMaskRequest() {
        }
        
        public GetAllMaskRequest(BloodDonor_01.OnnoRokomSms.GetAllMaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetAllMaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public GetAllMaskRequestBody() {
        }
        
        public GetAllMaskRequestBody(string apiKey) {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMaskResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public BloodDonor_01.OnnoRokomSms.GetAllMaskResponseBody Body;
        
        public GetAllMaskResponse() {
        }
        
        public GetAllMaskResponse(BloodDonor_01.OnnoRokomSms.GetAllMaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetAllMaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllMaskResult;
        
        public GetAllMaskResponseBody() {
        }
        
        public GetAllMaskResponseBody(string GetAllMaskResult) {
            this.GetAllMaskResult = GetAllMaskResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSmsSoapChannel : BloodDonor_01.OnnoRokomSms.SendSmsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSmsSoapClient : System.ServiceModel.ClientBase<BloodDonor_01.OnnoRokomSms.SendSmsSoap>, BloodDonor_01.OnnoRokomSms.SendSmsSoap {
        
        public SendSmsSoapClient() {
        }
        
        public SendSmsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSmsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSmsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSmsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodDonor_01.OnnoRokomSms.OneToOneBulkResponse BloodDonor_01.OnnoRokomSms.SendSmsSoap.OneToOneBulk(BloodDonor_01.OnnoRokomSms.OneToOneBulkRequest request) {
            return base.Channel.OneToOneBulk(request);
        }
        
        public string OneToOneBulk(BloodDonor_01.OnnoRokomSms.MessageHeader messageHeader, BloodDonor_01.OnnoRokomSms.WsSms[] wsSmses) {
            BloodDonor_01.OnnoRokomSms.OneToOneBulkRequest inValue = new BloodDonor_01.OnnoRokomSms.OneToOneBulkRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.OneToOneBulkRequestBody();
            inValue.Body.messageHeader = messageHeader;
            inValue.Body.wsSmses = wsSmses;
            BloodDonor_01.OnnoRokomSms.OneToOneBulkResponse retVal = ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).OneToOneBulk(inValue);
            return retVal.Body.OneToOneBulkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.OneToOneBulkResponse> BloodDonor_01.OnnoRokomSms.SendSmsSoap.OneToOneBulkAsync(BloodDonor_01.OnnoRokomSms.OneToOneBulkRequest request) {
            return base.Channel.OneToOneBulkAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.OneToOneBulkResponse> OneToOneBulkAsync(BloodDonor_01.OnnoRokomSms.MessageHeader messageHeader, BloodDonor_01.OnnoRokomSms.WsSms[] wsSmses) {
            BloodDonor_01.OnnoRokomSms.OneToOneBulkRequest inValue = new BloodDonor_01.OnnoRokomSms.OneToOneBulkRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.OneToOneBulkRequestBody();
            inValue.Body.messageHeader = messageHeader;
            inValue.Body.wsSmses = wsSmses;
            return ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).OneToOneBulkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodDonor_01.OnnoRokomSms.OneToOneResponse BloodDonor_01.OnnoRokomSms.SendSmsSoap.OneToOne(BloodDonor_01.OnnoRokomSms.OneToOneRequest request) {
            return base.Channel.OneToOne(request);
        }
        
        public string OneToOne(string userName, string userPassword, string mobileNumber, string smsText, string type, string maskName, string campaignName) {
            BloodDonor_01.OnnoRokomSms.OneToOneRequest inValue = new BloodDonor_01.OnnoRokomSms.OneToOneRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.OneToOneRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.mobileNumber = mobileNumber;
            inValue.Body.smsText = smsText;
            inValue.Body.type = type;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            BloodDonor_01.OnnoRokomSms.OneToOneResponse retVal = ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).OneToOne(inValue);
            return retVal.Body.OneToOneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.OneToOneResponse> BloodDonor_01.OnnoRokomSms.SendSmsSoap.OneToOneAsync(BloodDonor_01.OnnoRokomSms.OneToOneRequest request) {
            return base.Channel.OneToOneAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.OneToOneResponse> OneToOneAsync(string userName, string userPassword, string mobileNumber, string smsText, string type, string maskName, string campaignName) {
            BloodDonor_01.OnnoRokomSms.OneToOneRequest inValue = new BloodDonor_01.OnnoRokomSms.OneToOneRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.OneToOneRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.mobileNumber = mobileNumber;
            inValue.Body.smsText = smsText;
            inValue.Body.type = type;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).OneToOneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodDonor_01.OnnoRokomSms.OneToManyResponse BloodDonor_01.OnnoRokomSms.SendSmsSoap.OneToMany(BloodDonor_01.OnnoRokomSms.OneToManyRequest request) {
            return base.Channel.OneToMany(request);
        }
        
        public string OneToMany(string userName, string userPassword, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            BloodDonor_01.OnnoRokomSms.OneToManyRequest inValue = new BloodDonor_01.OnnoRokomSms.OneToManyRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.OneToManyRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.messageText = messageText;
            inValue.Body.numberList = numberList;
            inValue.Body.smsType = smsType;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            BloodDonor_01.OnnoRokomSms.OneToManyResponse retVal = ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).OneToMany(inValue);
            return retVal.Body.OneToManyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.OneToManyResponse> BloodDonor_01.OnnoRokomSms.SendSmsSoap.OneToManyAsync(BloodDonor_01.OnnoRokomSms.OneToManyRequest request) {
            return base.Channel.OneToManyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.OneToManyResponse> OneToManyAsync(string userName, string userPassword, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            BloodDonor_01.OnnoRokomSms.OneToManyRequest inValue = new BloodDonor_01.OnnoRokomSms.OneToManyRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.OneToManyRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.messageText = messageText;
            inValue.Body.numberList = numberList;
            inValue.Body.smsType = smsType;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).OneToManyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodDonor_01.OnnoRokomSms.DeliveryStatusResponse BloodDonor_01.OnnoRokomSms.SendSmsSoap.DeliveryStatus(BloodDonor_01.OnnoRokomSms.DeliveryStatusRequest request) {
            return base.Channel.DeliveryStatus(request);
        }
        
        public string DeliveryStatus(string userName, string userPassword, string responseId) {
            BloodDonor_01.OnnoRokomSms.DeliveryStatusRequest inValue = new BloodDonor_01.OnnoRokomSms.DeliveryStatusRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.DeliveryStatusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.responseId = responseId;
            BloodDonor_01.OnnoRokomSms.DeliveryStatusResponse retVal = ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).DeliveryStatus(inValue);
            return retVal.Body.DeliveryStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.DeliveryStatusResponse> BloodDonor_01.OnnoRokomSms.SendSmsSoap.DeliveryStatusAsync(BloodDonor_01.OnnoRokomSms.DeliveryStatusRequest request) {
            return base.Channel.DeliveryStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.DeliveryStatusResponse> DeliveryStatusAsync(string userName, string userPassword, string responseId) {
            BloodDonor_01.OnnoRokomSms.DeliveryStatusRequest inValue = new BloodDonor_01.OnnoRokomSms.DeliveryStatusRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.DeliveryStatusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.responseId = responseId;
            return ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).DeliveryStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodDonor_01.OnnoRokomSms.GetBalanceResponse BloodDonor_01.OnnoRokomSms.SendSmsSoap.GetBalance(BloodDonor_01.OnnoRokomSms.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public string GetBalance(string userName, string userPassword) {
            BloodDonor_01.OnnoRokomSms.GetBalanceRequest inValue = new BloodDonor_01.OnnoRokomSms.GetBalanceRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.GetBalanceRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            BloodDonor_01.OnnoRokomSms.GetBalanceResponse retVal = ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).GetBalance(inValue);
            return retVal.Body.GetBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetBalanceResponse> BloodDonor_01.OnnoRokomSms.SendSmsSoap.GetBalanceAsync(BloodDonor_01.OnnoRokomSms.GetBalanceRequest request) {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetBalanceResponse> GetBalanceAsync(string userName, string userPassword) {
            BloodDonor_01.OnnoRokomSms.GetBalanceRequest inValue = new BloodDonor_01.OnnoRokomSms.GetBalanceRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.GetBalanceRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            return ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).GetBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodDonor_01.OnnoRokomSms.GetMaskResponse BloodDonor_01.OnnoRokomSms.SendSmsSoap.GetMask(BloodDonor_01.OnnoRokomSms.GetMaskRequest request) {
            return base.Channel.GetMask(request);
        }
        
        public string GetMask(string userName, string userPassword) {
            BloodDonor_01.OnnoRokomSms.GetMaskRequest inValue = new BloodDonor_01.OnnoRokomSms.GetMaskRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.GetMaskRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            BloodDonor_01.OnnoRokomSms.GetMaskResponse retVal = ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).GetMask(inValue);
            return retVal.Body.GetMaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetMaskResponse> BloodDonor_01.OnnoRokomSms.SendSmsSoap.GetMaskAsync(BloodDonor_01.OnnoRokomSms.GetMaskRequest request) {
            return base.Channel.GetMaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetMaskResponse> GetMaskAsync(string userName, string userPassword) {
            BloodDonor_01.OnnoRokomSms.GetMaskRequest inValue = new BloodDonor_01.OnnoRokomSms.GetMaskRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.GetMaskRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            return ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).GetMaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodDonor_01.OnnoRokomSms.NumberSmsResponse BloodDonor_01.OnnoRokomSms.SendSmsSoap.NumberSms(BloodDonor_01.OnnoRokomSms.NumberSmsRequest request) {
            return base.Channel.NumberSms(request);
        }
        
        public string NumberSms(string apiKey, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            BloodDonor_01.OnnoRokomSms.NumberSmsRequest inValue = new BloodDonor_01.OnnoRokomSms.NumberSmsRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.NumberSmsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.messageText = messageText;
            inValue.Body.numberList = numberList;
            inValue.Body.smsType = smsType;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            BloodDonor_01.OnnoRokomSms.NumberSmsResponse retVal = ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).NumberSms(inValue);
            return retVal.Body.NumberSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.NumberSmsResponse> BloodDonor_01.OnnoRokomSms.SendSmsSoap.NumberSmsAsync(BloodDonor_01.OnnoRokomSms.NumberSmsRequest request) {
            return base.Channel.NumberSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.NumberSmsResponse> NumberSmsAsync(string apiKey, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            BloodDonor_01.OnnoRokomSms.NumberSmsRequest inValue = new BloodDonor_01.OnnoRokomSms.NumberSmsRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.NumberSmsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.messageText = messageText;
            inValue.Body.numberList = numberList;
            inValue.Body.smsType = smsType;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).NumberSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodDonor_01.OnnoRokomSms.ListSmsResponse BloodDonor_01.OnnoRokomSms.SendSmsSoap.ListSms(BloodDonor_01.OnnoRokomSms.ListSmsRequest request) {
            return base.Channel.ListSms(request);
        }
        
        public string ListSms(string apiKey, BloodDonor_01.OnnoRokomSms.WsSms[] wsSmses, string maskName, string campaignName) {
            BloodDonor_01.OnnoRokomSms.ListSmsRequest inValue = new BloodDonor_01.OnnoRokomSms.ListSmsRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.ListSmsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.wsSmses = wsSmses;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            BloodDonor_01.OnnoRokomSms.ListSmsResponse retVal = ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).ListSms(inValue);
            return retVal.Body.ListSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.ListSmsResponse> BloodDonor_01.OnnoRokomSms.SendSmsSoap.ListSmsAsync(BloodDonor_01.OnnoRokomSms.ListSmsRequest request) {
            return base.Channel.ListSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.ListSmsResponse> ListSmsAsync(string apiKey, BloodDonor_01.OnnoRokomSms.WsSms[] wsSmses, string maskName, string campaignName) {
            BloodDonor_01.OnnoRokomSms.ListSmsRequest inValue = new BloodDonor_01.OnnoRokomSms.ListSmsRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.ListSmsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.wsSmses = wsSmses;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).ListSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusResponse BloodDonor_01.OnnoRokomSms.SendSmsSoap.SMSDeliveryStatus(BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequest request) {
            return base.Channel.SMSDeliveryStatus(request);
        }
        
        public string SMSDeliveryStatus(string apiKey, string responseId) {
            BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequest inValue = new BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.responseId = responseId;
            BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusResponse retVal = ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).SMSDeliveryStatus(inValue);
            return retVal.Body.SMSDeliveryStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusResponse> BloodDonor_01.OnnoRokomSms.SendSmsSoap.SMSDeliveryStatusAsync(BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequest request) {
            return base.Channel.SMSDeliveryStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusResponse> SMSDeliveryStatusAsync(string apiKey, string responseId) {
            BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequest inValue = new BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.SMSDeliveryStatusRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.responseId = responseId;
            return ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).SMSDeliveryStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodDonor_01.OnnoRokomSms.GetCurrentBalanceResponse BloodDonor_01.OnnoRokomSms.SendSmsSoap.GetCurrentBalance(BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequest request) {
            return base.Channel.GetCurrentBalance(request);
        }
        
        public string GetCurrentBalance(string apiKey) {
            BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequest inValue = new BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequestBody();
            inValue.Body.apiKey = apiKey;
            BloodDonor_01.OnnoRokomSms.GetCurrentBalanceResponse retVal = ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).GetCurrentBalance(inValue);
            return retVal.Body.GetCurrentBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetCurrentBalanceResponse> BloodDonor_01.OnnoRokomSms.SendSmsSoap.GetCurrentBalanceAsync(BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequest request) {
            return base.Channel.GetCurrentBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetCurrentBalanceResponse> GetCurrentBalanceAsync(string apiKey) {
            BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequest inValue = new BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.GetCurrentBalanceRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).GetCurrentBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodDonor_01.OnnoRokomSms.GetAllMaskResponse BloodDonor_01.OnnoRokomSms.SendSmsSoap.GetAllMask(BloodDonor_01.OnnoRokomSms.GetAllMaskRequest request) {
            return base.Channel.GetAllMask(request);
        }
        
        public string GetAllMask(string apiKey) {
            BloodDonor_01.OnnoRokomSms.GetAllMaskRequest inValue = new BloodDonor_01.OnnoRokomSms.GetAllMaskRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.GetAllMaskRequestBody();
            inValue.Body.apiKey = apiKey;
            BloodDonor_01.OnnoRokomSms.GetAllMaskResponse retVal = ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).GetAllMask(inValue);
            return retVal.Body.GetAllMaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetAllMaskResponse> BloodDonor_01.OnnoRokomSms.SendSmsSoap.GetAllMaskAsync(BloodDonor_01.OnnoRokomSms.GetAllMaskRequest request) {
            return base.Channel.GetAllMaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodDonor_01.OnnoRokomSms.GetAllMaskResponse> GetAllMaskAsync(string apiKey) {
            BloodDonor_01.OnnoRokomSms.GetAllMaskRequest inValue = new BloodDonor_01.OnnoRokomSms.GetAllMaskRequest();
            inValue.Body = new BloodDonor_01.OnnoRokomSms.GetAllMaskRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((BloodDonor_01.OnnoRokomSms.SendSmsSoap)(this)).GetAllMaskAsync(inValue);
        }
    }
}
